import Head from 'next/head'
import Link from 'next/link'


  import styled from 'styled-components'


  //STYLES
  // const Content = styled.div`  
  // margin-left: 100px; 
  // padding: 0 55px;
  // color: #007ba5;
  // font-size: 20px;
  // text-align: center;
  // `
  const Wrapper = styled.div`
   padding: 150px;
 margin-top: 68px;
  `



   const Grid = styled.div`
   margin: 50px 150px;
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: 400px;  
  grid-template-areas: 
  'a b';
  grid-gap: 3em;
  
  
  @media only screen and (max-width: 1024px) {
   display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: repeat(2, 438px);
  grid-template-areas: 
  'a' 
  'b';
  }
  @media only screen and (max-width: 768px) {
      display: grid;
     grid-template-columns: 1fr;
     grid-template-rows: repeat(2, 238px);
     grid-template-areas: 
     'a' 
     'b';
 
     }
  
  `
   const LeftSide = styled.div`
   grid-area: a;
   border: solid 1px black; 
  background: #3aa1aa;

  ` 
  
   const RightSide = styled.div`
   grid-area: b;
   border: solid 1px black; 
  background: #3aa1aa;

  `   

 

  const GridTitle = styled.div`
  font-size: 35px;
     color: #007ba5;
     text-align: center;
     text-decoration: underline;
     padding-top: 55px;
     @media only screen and (max-width: 768px) {
       font-size: 30px;
     }
  `
 
  const ProjectLink = styled.div`
  text-align: center;
  margin: 45px;
  cursor: pointer;
  font-size: 30px;

  a {
    text-decoration: none;
   color: aquamarine;
  }
  a:hover {
    color: #fff;
    transition: 1s;
    text-decoration: underline;
  }
  }
  @media only screen and (max-width: 768px) {
    margin: 15px;
    a{
    }
   }
  `
  //END STYLES







const Projects = () => {
   return (
     <>
     <Head>
     <title>Elsa Hovey | Creative Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <Wrapper>

      {/* <Content> Lorem ipsum dolor sit amet consectetur, a! Quos dicta unde incidunt laudantium?</Content> */}
  
     <Grid>
      <LeftSide>
      <GridTitle>Writing Projects</GridTitle>

          <ProjectLink>
          <Link href="/creative-projects/on-finding-creativity"> 
            Css Gallery
            </Link>
            </ProjectLink>

          <ProjectLink>
          <Link href="/creative-projects/website-case-studies"> 
           Website Templates
            </Link>
                </ProjectLink>
      </LeftSide> 
      
 
       
      <RightSide>
          <GridTitle>Javascript Projects</GridTitle>
      <ProjectLink>
        <Link href="/creative-projects/gallery"> 
      Data Stuctures and Algorithms
       </Link>
       </ProjectLink>
      <ProjectLink>
       <Link href="/creative-projects/javascript-css-gallery"> 
        Misc Projects
       </Link>
       </ProjectLink>
       

     </RightSide>
     </Grid>
   
     </Wrapper>
     </>
   )
 }
 
 
export default Projects
