import Head from 'next/head'
import { sanityClient, urlFor } from "../client"
import {
Grid,
LeftSide,
RightSide
} from '../components/styles/GridStyles.js'

import styled from 'styled-components'






//STYLES
export const Intro = styled.div`
display: flex;
justify-content: center;
align-items: center;
margin: 55px;
`
export const ImageWrapper = styled.div`
margin: 10px;
.portfolio-img{
  border: solid 2px black;
  width: 250px;
  height: 400px;
  @media only screen and (max-width: 810px) {
    width: 50px;
    height: 50px;
  }

}

`

export const IntroContent = styled.div`
display: flex;
justify-content: center;
flex-direction: column;
font-size: 20px;
margin: 15px;
h3 {
  margin: 15px 0;
}
`



export const SkillsWrapper = styled.div`
margin: 25px;
display: flex;
justify-content: center;
flex-direction: column;
`


export const SkillsList = styled.ul`
margin: 20px;
width: 400px;
h3 {
  font-size: 20px;
  text-decoration: underline;
}
 li{
  margin: 10px;
  font-size: 17px;
 }
@media only screen and (max-width: 768px) {
  margin: 20px;
}
`


//icons

export const MasterWrapper = styled.div`
display: flex;
`

export const Wrapper = styled.div`
 display: flex;
 justify-content: center;
 align-items: center;
 margin: 65px;  

@media only screen and (max-width: 968px) {
margin: 0;
}
@media only screen and (max-width: 768px) {
}
`;


export const Title = styled.div`
text-align: center;
padding: 25px;
font-size: 25px;
color: aquamarine;
@media only screen and (max-width: 768px) {
    margin-top: 105px;
    padding: 0;
    font-size: 35px;

}   
`

const IconGrid = styled.div`
width: 400px;
height: 350px;
display: grid;
grid-template-columns: repeat(4, 1fr);
grid-gap: 1em;  
.img {
    background: teal;
    border-radius: 25px;
    width: 75px;
    height: 75px;
}
@media only screen and (max-width: 1024px) {
}   

@media only screen and (max-width: 768px) {
  background: blue;
  margin-bottom: 100px;
}   
`

export const SkillsTitle = styled.div`
 text-align: center;
 width: 70%;
 font-size: 12px;
@media only screen and (max-width: 768px) {
}   
` 
//END STYLES


 



 const About = ({posts}) => {
   return (
     <>
     <Head>
        <title>Elsa Hovey | skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Grid>
      <LeftSide>
  
            <Intro>
              <ImageWrapper>
                  <img
                      className='portfolio-img'
                      src='images/portfolio-pic.jpg'
                      alt='portfolio pic'
                
                      />
                      </ImageWrapper>
                      <IntroContent>
                        <h3>Hello! Im Elsa.</h3>
                        <p> Im currently working as a freelance web developer while building up my own side projects.
                        I like to keep multiple hobbies and small business projects, and have created websites to keep track of my progress. My curiosity is what keeps me going, along with the desire to help other people with their endeavors.</p>
                        </IntroContent>
             </Intro>

   
   
      </LeftSide>
      

      {/* 
      //*RIGHT
       */}
       
      <RightSide>
      <Title>What I Do</Title>
      <MasterWrapper>
      <SkillsWrapper>
                 <SkillsList>
                  <h3>Frontend Web Design</h3> 
                          <li>Colorful websites for creative niches and small businesses.</li>
                          <li>Quick and interactive styling</li>
                          <li>Effective SEO</li>
                      </SkillsList>  
             
 
                      <SkillsList>
                      <h3>Content Management</h3>  
                          <li>Currently using Sanity.io for content writing, image management, and backend data storage</li>
                          <li>I work one on one with customers to create the ideal website product</li>
                          <li>In my freetime, I also work and manage my
                            <a href="/websites">own projects</a>
                              </li>
                      </SkillsList> 
                      </SkillsWrapper>
      <Wrapper>
        <IconGrid>
        {posts &&
        posts.map((post, index) => (   
          <span key={index}>
                <img
                className="img"
                src={urlFor(post.icon)}
            
                />
    <SkillsTitle>{post.name}</SkillsTitle>

  </span>
  ))}
</IconGrid>
</Wrapper>
</MasterWrapper>
     </RightSide>
     </Grid>
     </>
   )
 }
 
 export const getServerSideProps = async () => {
  const query = '*[ _type == "skills"] | order(_createdAt desc)[0..9]'
  const posts = await sanityClient.fetch(query)

  if (!posts.length) {
    return {
      props: {
        posts: [],
      },
    }
  } else {
    return {
      props: {
        posts,
      },
    }
  }
}
 

 export default About