import Head from 'next/head'
import Link from "next/link"
import styled from 'styled-components'
import { sanityClient } from '../client'
import SubscribeForm from '../components/SubscribeForm'



//STYLES 
 const Wrapper = styled.div`
 background: #3aa1aa;
@media only screen and (max-width: 1024px) {
}
@media only screen and (max-width: 768px) {
  padding: auto;
  margin: 55px 0 0 0;
}
 ` 
//  const Title = styled.div`
//  display: flex;
//  justify-content: center;
//  padding: 60px 0 0 0;
//  font-size: 35px;
//  color: #007ba5;
//  text-decoration: underline;
// @media only screen and (max-width: 1024px) {
// }
// `

const SubscribeTitle = styled.div`
display: flex;
justify-content: center;
padding: 60px 0 0 0;
font-size: 35px;
text-decoration: underline;
`

const Grid = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: 1fr;  
  grid-template-areas: 
  'a b';

@media only screen and (max-width: 1024px) {
  display: grid;
  grid-template-columns: 1fr; 
  grid-template-rows: repeat(2, 1fr);
  grid-template-areas: 
  'b'
  'a';
}
@media only screen and (max-width: 768px) {
}

`
const LeftSide = styled.div`
border-right: solid 2px black;
display: flex;
justify-content: center;
padding-top: 100px;
grid-area: a;
p {
  font-size: 20px;  
}
@media only screen and (max-width: 1024px) {
  border: none;
}
`
const RightSide = styled.div`
grid-area: b;
padding: 120px 50px 180px;
`

const Title = styled.h2`
padding: 25px 0;
font-size: 30px;
`



 const PostTitle = styled.div`
 font-weight: bold;
 font-size: 30px;
 text-decoration: underline;
 color: #007ba5;
 cursor: pointer;
`

const Date = styled.div`

`

const Description = styled.div`
font-size: 20px;
@media only screen and (max-width: 768px) {

}
`

const SubscribeWrapper = styled.div`
background: #3aa1aa;
height: 380px;
h2 {
  text-align: center;
  padding: 25px;
}
p {
  padding: 20px;
}
@media only screen and (max-width: 768px) {
margin: 25px;
}
`
//END STYLES



 const Projects = ({posts}) => {
   return (
     <>
     <Head>
        <title>Elsa Hovey | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Wrapper>
       {/* <Title>Blog</Title> */}
     
     <Grid>
      
      <LeftSide>
        <SubscribeWrapper>
        <SubscribeTitle>Subscribe Form</SubscribeTitle>
        <p>I write about my progress as a web developer, and document my projects.</p>
        <SubscribeForm />
        </SubscribeWrapper>      
        </LeftSide>

        <RightSide>
          <Title>Recent Posts</Title>
          {posts &&
          posts.map((post, index) => (
            // eslint-disable-next-line react/jsx-key
            <Link href={`post/${post.slug.current}`}>
            <span key={index}>
              <PostTitle>{post.title}</PostTitle>
              <Date>date</Date>
              <Description>{post.description}</Description>
            </span>
            </Link>
          ))
          }
        </RightSide>

       </Grid>
       </Wrapper>
     </>
   )
 }


 export const getServerSideProps = async() => {
    const query = '*[_type == "post"] | order(_createdAt desc)[0..4]'
    const posts = await sanityClient.fetch(query)

    if (!posts.length) {
      return {
        props: {
          posts: [],
        },
      }
    } else {
      return {
      props: {
        posts,
      }
    }
 }
}
  
 

 export default Projects