import Head from 'next/head'
 
 
  

import styled from 'styled-components'






//STYLES 
 
 
//END STYLES


 



 const Projects = () => {
   return (
     <>
     <Head>
        <title>Elsa Hovey | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
     </>
   )
 }
  
 

 export default Projects