import Head from 'next/head'
import {
  HomeLeft,
  HomeRight,
} from '../components/styles/IndexGrid.styled'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Elsa Hovey | Development/ Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className="main-grid"
        data-aos='zoom-in'
         data-aos-duration='1000'
         data-aos-once='true'
         data-aos-anchor-placement='center bottom'
   >
       <HomeLeft>
           <div className="jtpic">
            
           <img
            className='jt-img'
            src='images/joshuatreeabout.png'
            alt='joshua tree'
            />
              </div>
              </HomeLeft>

              <HomeRight>
             <h2 className="intro">{"Hi there, I'm Elsa"}</h2>         
             <span className="about-me">{"I'm a web developer based in Joshua Tree, CA. I create niche websites and solutions for small business owners and creatives. "}</span>
        </HomeRight>
        </div>
    </div>
  )
}
  