import Head from 'next/head'
import IndexGrid from '../components/IndexGrid'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Elsa Hovey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexGrid />
    </div>
  )
}
