import Head from 'next/head'
import Link from 'next/link'
import {
  Grid,
  LeftSide,
  RightSide
  } from '../components/styles/GridStyles.js'

  import styled from 'styled-components'



  //STYLES
  const Title = styled.div`
  font-size: 35px;
     color: #007ba5;
     text-align: center;
     text-decoration: underline;
     padding-top: 105px;
     @media only screen and (max-width: 768px) {
       font-size: 30px;
     }
  `
 
  const ProjectLink = styled.div`
  text-align: center;
  margin: 45px;
  cursor: pointer;
  a {
    text-decoration: none;
   color: aquamarine;
  font-size: 30px;
  }
  a:hover {
    color: #fff;
    transition: 1s;
    text-decoration: underline;
  }
  }
  @media only screen and (max-width: 768px) {
    margin: 15px;
    a{
    }
   }
  `
  //END STYLES







const Projects = () => {
   return (
     <>
     <Head>
     <title>Elsa Hovey | Creative Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



     <Grid>
      <LeftSide>
      <Title>Writing Projects</Title>

          <ProjectLink>
          <Link href="/creative-projects/on-finding-creativity"> 
      On Finding Creativity
            </Link>
            </ProjectLink>

          <ProjectLink>
          <Link href="/creative-projects/website-case-studies"> 
           Website Case Studies  
            </Link>
                </ProjectLink>
      </LeftSide>
      
 
       
      <RightSide>
          <Title>Web Dev Projects</Title>
      <ProjectLink>
        <Link href="/creative-projects/gallery"> 
      Graphic Arts Gallery
       </Link>
       </ProjectLink>
      <ProjectLink>
       <Link href="/creative-projects/javascript-css-gallery"> 
        Javascript Projects
       </Link>
       </ProjectLink>
       

     </RightSide>
     </Grid>



     </>
   )
 }
 
 
export default Projects
