/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Link from "next/link"

import { sanityClient } from "../client"

// import {
// Title, 
// Wrapper,    
// Grid,
// PostTitles,
// } from '../components/styles/StudyGuide.styled'
import styled from 'styled-components'


//STYLES
const Title = styled.h2`
text-align: center; 
padding: 20px;
`

const Wrapper = styled.div`
display: flex;
justify-content: center;
// background: maroon;
`
const Grid = styled.div`
display: grid;
grid-template-columns: repeat(2, 800px);
grid-template-rows: repeat(2, 1fr);
grid-gap: 1em;
cursor: pointer;
.square {
    display: flex;
    justify-content: center;
    // background: green;

}
`
 
//END STYLES






export default function test({categories}) {
  return (
    <>  
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>     
      
     <Title>Blog</Title>
     <Wrapper> 
       <Grid>
       {categories &&
        categories.map((category, index) => (   
          <span key={index}>
            <Link href={`category/${category.slug.current}`}>
            <div className="square">
          <h3>{category.title}</h3>
      
          </div>
          </Link>
          </span>
          ))}
          </Grid>
          </Wrapper>
    </>
  )
}


export const getServerSideProps = async () => {
  const query = '*[ _type == "category"] '
  const categories = await sanityClient.fetch(query)

  if (!categories.length) {
    return {
      props: {
        categories: [],
      },
    }
  } else {
    return {
      props: {
        categories,
      },
    }
  }
}
 